model_checkpoint: ybelkada/blip2-opt-2.7b-fp16-sharded
processor_checkpoint: "Salesforce/blip2-opt-2.7b"

dataset_name: aidystark/shoeBlip
wandb_name: captioning_project

hub: q_shoe
pretrained_model: "Salesforce/blip2-opt-2.7b"
num_classes: 2
lr: 2e-5
weight_decay: 0.0
lora_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: "none"
  target_modules:
    - "q_proj"
    - "k_proj"
training_params:
  max_epochs: 5
  accelerator: "auto"
  batch_size: 4
  project: "blip2-training"